[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
learn_vault = "5ZcAT1AQBhQdcj7pMo4zq4SvjmqM8NgBZ1nBWRSgAWLp"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
